/**
 * node-express-boilerplate API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body7 model module.
* @module model/Body7
* @version 1.6.0
*/
export default class Body7 {
    /**
    * Constructs a new <code>Body7</code>.
    * @alias module:model/Body7
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body7</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body7} obj Optional instance to populate.
    * @return {module:model/Body7} The populated <code>Body7</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body7();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;




}
