/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Body19 model module.
 * @module model/Body19
 * @version 1.6.0
 */
class Body19 {
    /**
     * Constructs a new <code>Body19</code>.
     * @alias module:model/Body19
     */
    constructor() { 
        
        Body19.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Body19</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body19} obj Optional instance to populate.
     * @return {module:model/Body19} The populated <code>Body19</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body19();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('education')) {
                obj['education'] = ApiClient.convertToType(data['education'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('aboutMe')) {
                obj['aboutMe'] = ApiClient.convertToType(data['aboutMe'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Body19.prototype['name'] = undefined;

/**
 * must be unique
 * @member {String} email
 */
Body19.prototype['email'] = undefined;

/**
 * @member {String} company
 */
Body19.prototype['company'] = undefined;

/**
 * @member {String} education
 */
Body19.prototype['education'] = undefined;

/**
 * @member {String} address
 */
Body19.prototype['address'] = undefined;

/**
 * @member {String} city
 */
Body19.prototype['city'] = undefined;

/**
 * @member {String} country
 */
Body19.prototype['country'] = undefined;

/**
 * @member {String} postalCode
 */
Body19.prototype['postalCode'] = undefined;

/**
 * @member {String} aboutMe
 */
Body19.prototype['aboutMe'] = undefined;






export default Body19;

