/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TasksbulkTasks from './TasksbulkTasks';

/**
 * The Body13 model module.
 * @module model/Body13
 * @version 1.6.0
 */
class Body13 {
    /**
     * Constructs a new <code>Body13</code>.
     * @alias module:model/Body13
     * @param tasks {Array.<module:model/TasksbulkTasks>} 
     */
    constructor(tasks) { 
        
        Body13.initialize(this, tasks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tasks) { 
        obj['tasks'] = tasks;
    }

    /**
     * Constructs a <code>Body13</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body13} obj Optional instance to populate.
     * @return {module:model/Body13} The populated <code>Body13</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body13();

            if (data.hasOwnProperty('tasks')) {
                obj['tasks'] = ApiClient.convertToType(data['tasks'], [TasksbulkTasks]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TasksbulkTasks>} tasks
 */
Body13.prototype['tasks'] = undefined;






export default Body13;

