/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvoicesbulkInvoices from './InvoicesbulkInvoices';

/**
 * The Body8 model module.
 * @module model/Body8
 * @version 1.6.0
 */
class Body8 {
    /**
     * Constructs a new <code>Body8</code>.
     * @alias module:model/Body8
     * @param invoices {Array.<module:model/InvoicesbulkInvoices>} 
     */
    constructor(invoices) { 
        
        Body8.initialize(this, invoices);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, invoices) { 
        obj['invoices'] = invoices;
    }

    /**
     * Constructs a <code>Body8</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body8} obj Optional instance to populate.
     * @return {module:model/Body8} The populated <code>Body8</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body8();

            if (data.hasOwnProperty('invoices')) {
                obj['invoices'] = ApiClient.convertToType(data['invoices'], [InvoicesbulkInvoices]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/InvoicesbulkInvoices>} invoices
 */
Body8.prototype['invoices'] = undefined;






export default Body8;

