/**
 * SprintService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Body6 model module.
 * @module model/Body6
 * @version 1.6.0
 */
class Body6 {
    /**
     * Constructs a new <code>Body6</code>.
     * @alias module:model/Body6
     * @param name {String} 
     * @param teamId {String} 
     */
    constructor(name, teamId) { 
        
        Body6.initialize(this, name, teamId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, teamId) { 
        obj['name'] = name;
        obj['teamId'] = teamId;
    }

    /**
     * Constructs a <code>Body6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body6} obj Optional instance to populate.
     * @return {module:model/Body6} The populated <code>Body6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body6();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('teamId')) {
                obj['teamId'] = ApiClient.convertToType(data['teamId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Body6.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Body6.prototype['description'] = undefined;

/**
 * @member {String} teamId
 */
Body6.prototype['teamId'] = undefined;






export default Body6;

