/**
 * SprintService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Body1 model module.
 * @module model/Body1
 * @version 1.6.0
 */
class Body1 {
    /**
     * Constructs a new <code>Body1</code>.
     * @alias module:model/Body1
     * @param email {String} 
     * @param password {String} 
     */
    constructor(email, password) { 
        
        Body1.initialize(this, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password) { 
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>Body1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body1} obj Optional instance to populate.
     * @return {module:model/Body1} The populated <code>Body1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body1();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
Body1.prototype['email'] = undefined;

/**
 * @member {String} password
 */
Body1.prototype['password'] = undefined;






export default Body1;

