/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TasksbulkTasks from './TasksbulkTasks';

/**
 * The Body8 model module.
 * @module model/Body8
 * @version 1.6.0
 */
class Body8 {
    /**
     * Constructs a new <code>Body8</code>.
     * @alias module:model/Body8
     * @param backlogId {String} 
     * @param tasks {Array.<module:model/TasksbulkTasks>} 
     */
    constructor(backlogId, tasks) { 
        
        Body8.initialize(this, backlogId, tasks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, backlogId, tasks) { 
        obj['backlogId'] = backlogId;
        obj['tasks'] = tasks;
    }

    /**
     * Constructs a <code>Body8</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body8} obj Optional instance to populate.
     * @return {module:model/Body8} The populated <code>Body8</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body8();

            if (data.hasOwnProperty('backlogId')) {
                obj['backlogId'] = ApiClient.convertToType(data['backlogId'], 'String');
            }
            if (data.hasOwnProperty('tasks')) {
                obj['tasks'] = ApiClient.convertToType(data['tasks'], [TasksbulkTasks]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} backlogId
 */
Body8.prototype['backlogId'] = undefined;

/**
 * @member {Array.<module:model/TasksbulkTasks>} tasks
 */
Body8.prototype['tasks'] = undefined;






export default Body8;

