/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Task from './Task';

/**
 * The TaskEvent model module.
 * @module model/TaskEvent
 * @version 1.6.0
 */
class TaskEvent {
    /**
     * Constructs a new <code>TaskEvent</code>.
     * @alias module:model/TaskEvent
     */
    constructor() { 
        
        TaskEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaskEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaskEvent} obj Optional instance to populate.
     * @return {module:model/TaskEvent} The populated <code>TaskEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskEvent();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('tid')) {
                obj['tid'] = ApiClient.convertToType(data['tid'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = Task.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
TaskEvent.prototype['type'] = undefined;

/**
 * @member {String} tid
 */
TaskEvent.prototype['tid'] = undefined;

/**
 * @member {module:model/Task} data
 */
TaskEvent.prototype['data'] = undefined;






export default TaskEvent;

