/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Task from './Task';

/**
 * The TasksbulkTasks model module.
 * @module model/TasksbulkTasks
 * @version 1.6.0
 */
class TasksbulkTasks {
    /**
     * Constructs a new <code>TasksbulkTasks</code>.
     * @alias module:model/TasksbulkTasks
     */
    constructor() { 
        
        TasksbulkTasks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TasksbulkTasks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TasksbulkTasks} obj Optional instance to populate.
     * @return {module:model/TasksbulkTasks} The populated <code>TasksbulkTasks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TasksbulkTasks();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = Task.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
TasksbulkTasks.prototype['type'] = undefined;

/**
 * @member {String} taskId
 */
TasksbulkTasks.prototype['taskId'] = undefined;

/**
 * @member {module:model/Task} data
 */
TasksbulkTasks.prototype['data'] = undefined;






export default TasksbulkTasks;

