/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Body8 from '../model/Body8';
import Body9 from '../model/Body9';
import Error from '../model/Error';
import InlineResponse2001 from '../model/InlineResponse2001';
import Invoice from '../model/Invoice';
import InvoiceEvent from '../model/InvoiceEvent';

/**
* Invoices service.
* @module api/InvoicesApi
* @version 1.6.0
*/
export default class InvoicesApi {

    /**
    * Constructs a new InvoicesApi. 
    * @alias module:api/InvoicesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create a invoice events
     * User can create invoice events.
     * @param {module:model/Body8} Body8 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InvoiceEvent} and HTTP response
     */
    invoicesBulkPostWithHttpInfo(Body8) {
      let postBody = Body8;
      // verify the required parameter 'Body8' is set
      if (Body8 === undefined || Body8 === null) {
        throw new Error("Missing the required parameter 'Body8' when calling invoicesBulkPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InvoiceEvent;
      return this.apiClient.callApi(
        '/invoices/bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a invoice events
     * User can create invoice events.
     * @param {module:model/Body8} Body8 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InvoiceEvent}
     */
    invoicesBulkPost(Body8) {
      return this.invoicesBulkPostWithHttpInfo(Body8)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get all invoices
     * Logged in invoice can retrieve all invoices.
     * @param {String} teamId invoice teamId
     * @param {Object} opts Optional parameters
     * @param {String} opts.name invoice client name
     * @param {String} opts.status invoice status
     * @param {String} opts.description invoice project / description
     * @param {String} opts.sortBy sort by query in the form of field:desc/asc (ex. name:asc)
     * @param {Number} opts.limit Maximum number of invoices
     * @param {Number} opts.page Page number (default to 1)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2001} and HTTP response
     */
    invoicesGetWithHttpInfo(teamId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'teamId' is set
      if (teamId === undefined || teamId === null) {
        throw new Error("Missing the required parameter 'teamId' when calling invoicesGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'teamId': teamId,
        'name': opts['name'],
        'status': opts['status'],
        'description': opts['description'],
        'sortBy': opts['sortBy'],
        'limit': opts['limit'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;
      return this.apiClient.callApi(
        '/invoices', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get all invoices
     * Logged in invoice can retrieve all invoices.
     * @param {String} teamId invoice teamId
     * @param {Object} opts Optional parameters
     * @param {String} opts.name invoice client name
     * @param {String} opts.status invoice status
     * @param {String} opts.description invoice project / description
     * @param {String} opts.sortBy sort by query in the form of field:desc/asc (ex. name:asc)
     * @param {Number} opts.limit Maximum number of invoices
     * @param {Number} opts.page Page number (default to 1)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2001}
     */
    invoicesGet(teamId, opts) {
      return this.invoicesGetWithHttpInfo(teamId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get all invoices
     * User can retrieve assigned invoices.
     * @param {String} invoiceId Invoice id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Invoice} and HTTP response
     */
    invoicesInvoiceIdGetWithHttpInfo(invoiceId) {
      let postBody = null;
      // verify the required parameter 'invoiceId' is set
      if (invoiceId === undefined || invoiceId === null) {
        throw new Error("Missing the required parameter 'invoiceId' when calling invoicesInvoiceIdGet");
      }

      let pathParams = {
        'invoiceId': invoiceId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Invoice;
      return this.apiClient.callApi(
        '/invoices/{invoiceId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get all invoices
     * User can retrieve assigned invoices.
     * @param {String} invoiceId Invoice id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Invoice}
     */
    invoicesInvoiceIdGet(invoiceId) {
      return this.invoicesInvoiceIdGetWithHttpInfo(invoiceId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a invoice event
     * User can create invoice event.
     * @param {module:model/Body9} Body9 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InvoiceEvent} and HTTP response
     */
    invoicesPostWithHttpInfo(Body9) {
      let postBody = Body9;
      // verify the required parameter 'Body9' is set
      if (Body9 === undefined || Body9 === null) {
        throw new Error("Missing the required parameter 'Body9' when calling invoicesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InvoiceEvent;
      return this.apiClient.callApi(
        '/invoices', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a invoice event
     * User can create invoice event.
     * @param {module:model/Body9} Body9 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InvoiceEvent}
     */
    invoicesPost(Body9) {
      return this.invoicesPostWithHttpInfo(Body9)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
