/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthTokens from './model/AuthTokens';
import Backlog from './model/Backlog';
import Body from './model/Body';
import Body1 from './model/Body1';
import Body10 from './model/Body10';
import Body11 from './model/Body11';
import Body12 from './model/Body12';
import Body13 from './model/Body13';
import Body14 from './model/Body14';
import Body15 from './model/Body15';
import Body16 from './model/Body16';
import Body17 from './model/Body17';
import Body18 from './model/Body18';
import Body19 from './model/Body19';
import Body2 from './model/Body2';
import Body20 from './model/Body20';
import Body21 from './model/Body21';
import Body3 from './model/Body3';
import Body4 from './model/Body4';
import Body5 from './model/Body5';
import Body6 from './model/Body6';
import Body7 from './model/Body7';
import Body8 from './model/Body8';
import Body9 from './model/Body9';
import Contact from './model/Contact';
import Error from './model/Error';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse201 from './model/InlineResponse201';
import Invoice from './model/Invoice';
import InvoiceEvent from './model/InvoiceEvent';
import InvoiceItems from './model/InvoiceItems';
import InvoiceRecipient from './model/InvoiceRecipient';
import InvoicesbulkInvoices from './model/InvoicesbulkInvoices';
import Organization from './model/Organization';
import Task from './model/Task';
import TaskEvent from './model/TaskEvent';
import TasksbulkTasks from './model/TasksbulkTasks';
import Team from './model/Team';
import Token from './model/Token';
import User from './model/User';
import Widget from './model/Widget';
import AuthApi from './api/AuthApi';
import BacklogsApi from './api/BacklogsApi';
import ContactsApi from './api/ContactsApi';
import InviteesApi from './api/InviteesApi';
import InvoicesApi from './api/InvoicesApi';
import OrganizationsApi from './api/OrganizationsApi';
import TasksApi from './api/TasksApi';
import TeamsApi from './api/TeamsApi';
import UsersApi from './api/UsersApi';
import WidgetsApi from './api/WidgetsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SprintService = require('index'); // See note below*.
* var xxxSvc = new SprintService.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SprintService.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SprintService.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SprintService.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.6.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthTokens model constructor.
     * @property {module:model/AuthTokens}
     */
    AuthTokens,

    /**
     * The Backlog model constructor.
     * @property {module:model/Backlog}
     */
    Backlog,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The Body1 model constructor.
     * @property {module:model/Body1}
     */
    Body1,

    /**
     * The Body10 model constructor.
     * @property {module:model/Body10}
     */
    Body10,

    /**
     * The Body11 model constructor.
     * @property {module:model/Body11}
     */
    Body11,

    /**
     * The Body12 model constructor.
     * @property {module:model/Body12}
     */
    Body12,

    /**
     * The Body13 model constructor.
     * @property {module:model/Body13}
     */
    Body13,

    /**
     * The Body14 model constructor.
     * @property {module:model/Body14}
     */
    Body14,

    /**
     * The Body15 model constructor.
     * @property {module:model/Body15}
     */
    Body15,

    /**
     * The Body16 model constructor.
     * @property {module:model/Body16}
     */
    Body16,

    /**
     * The Body17 model constructor.
     * @property {module:model/Body17}
     */
    Body17,

    /**
     * The Body18 model constructor.
     * @property {module:model/Body18}
     */
    Body18,

    /**
     * The Body19 model constructor.
     * @property {module:model/Body19}
     */
    Body19,

    /**
     * The Body2 model constructor.
     * @property {module:model/Body2}
     */
    Body2,

    /**
     * The Body20 model constructor.
     * @property {module:model/Body20}
     */
    Body20,

    /**
     * The Body21 model constructor.
     * @property {module:model/Body21}
     */
    Body21,

    /**
     * The Body3 model constructor.
     * @property {module:model/Body3}
     */
    Body3,

    /**
     * The Body4 model constructor.
     * @property {module:model/Body4}
     */
    Body4,

    /**
     * The Body5 model constructor.
     * @property {module:model/Body5}
     */
    Body5,

    /**
     * The Body6 model constructor.
     * @property {module:model/Body6}
     */
    Body6,

    /**
     * The Body7 model constructor.
     * @property {module:model/Body7}
     */
    Body7,

    /**
     * The Body8 model constructor.
     * @property {module:model/Body8}
     */
    Body8,

    /**
     * The Body9 model constructor.
     * @property {module:model/Body9}
     */
    Body9,

    /**
     * The Contact model constructor.
     * @property {module:model/Contact}
     */
    Contact,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The Invoice model constructor.
     * @property {module:model/Invoice}
     */
    Invoice,

    /**
     * The InvoiceEvent model constructor.
     * @property {module:model/InvoiceEvent}
     */
    InvoiceEvent,

    /**
     * The InvoiceItems model constructor.
     * @property {module:model/InvoiceItems}
     */
    InvoiceItems,

    /**
     * The InvoiceRecipient model constructor.
     * @property {module:model/InvoiceRecipient}
     */
    InvoiceRecipient,

    /**
     * The InvoicesbulkInvoices model constructor.
     * @property {module:model/InvoicesbulkInvoices}
     */
    InvoicesbulkInvoices,

    /**
     * The Organization model constructor.
     * @property {module:model/Organization}
     */
    Organization,

    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task,

    /**
     * The TaskEvent model constructor.
     * @property {module:model/TaskEvent}
     */
    TaskEvent,

    /**
     * The TasksbulkTasks model constructor.
     * @property {module:model/TasksbulkTasks}
     */
    TasksbulkTasks,

    /**
     * The Team model constructor.
     * @property {module:model/Team}
     */
    Team,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The Widget model constructor.
     * @property {module:model/Widget}
     */
    Widget,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The BacklogsApi service constructor.
    * @property {module:api/BacklogsApi}
    */
    BacklogsApi,

    /**
    * The ContactsApi service constructor.
    * @property {module:api/ContactsApi}
    */
    ContactsApi,

    /**
    * The InviteesApi service constructor.
    * @property {module:api/InviteesApi}
    */
    InviteesApi,

    /**
    * The InvoicesApi service constructor.
    * @property {module:api/InvoicesApi}
    */
    InvoicesApi,

    /**
    * The OrganizationsApi service constructor.
    * @property {module:api/OrganizationsApi}
    */
    OrganizationsApi,

    /**
    * The TasksApi service constructor.
    * @property {module:api/TasksApi}
    */
    TasksApi,

    /**
    * The TeamsApi service constructor.
    * @property {module:api/TeamsApi}
    */
    TeamsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The WidgetsApi service constructor.
    * @property {module:api/WidgetsApi}
    */
    WidgetsApi
};
