/**
 * node-express-boilerplate API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeExpressBoilerplateApiDocumentation);
  }
}(this, function(expect, NodeExpressBoilerplateApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeExpressBoilerplateApiDocumentation.AuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthApi', function() {
    describe('authForgotPasswordPost', function() {
      it('should call authForgotPasswordPost successfully', function(done) {
        //uncomment below and update the code to test authForgotPasswordPost
        //instance.authForgotPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authLoginPost', function() {
      it('should call authLoginPost successfully', function(done) {
        //uncomment below and update the code to test authLoginPost
        //instance.authLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authLogoutPost', function() {
      it('should call authLogoutPost successfully', function(done) {
        //uncomment below and update the code to test authLogoutPost
        //instance.authLogoutPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authRefreshTokensPost', function() {
      it('should call authRefreshTokensPost successfully', function(done) {
        //uncomment below and update the code to test authRefreshTokensPost
        //instance.authRefreshTokensPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authRegisterPost', function() {
      it('should call authRegisterPost successfully', function(done) {
        //uncomment below and update the code to test authRegisterPost
        //instance.authRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authResetPasswordPost', function() {
      it('should call authResetPasswordPost successfully', function(done) {
        //uncomment below and update the code to test authResetPasswordPost
        //instance.authResetPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
