/**
 * node-express-boilerplate API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeExpressBoilerplateApiDocumentation);
  }
}(this, function(expect, NodeExpressBoilerplateApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeExpressBoilerplateApiDocumentation.BacklogsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BacklogsApi', function() {
    describe('backlogsGet', function() {
      it('should call backlogsGet successfully', function(done) {
        //uncomment below and update the code to test backlogsGet
        //instance.backlogsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backlogsIdDelete', function() {
      it('should call backlogsIdDelete successfully', function(done) {
        //uncomment below and update the code to test backlogsIdDelete
        //instance.backlogsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backlogsIdGet', function() {
      it('should call backlogsIdGet successfully', function(done) {
        //uncomment below and update the code to test backlogsIdGet
        //instance.backlogsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backlogsIdPatch', function() {
      it('should call backlogsIdPatch successfully', function(done) {
        //uncomment below and update the code to test backlogsIdPatch
        //instance.backlogsIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('backlogsPost', function() {
      it('should call backlogsPost successfully', function(done) {
        //uncomment below and update the code to test backlogsPost
        //instance.backlogsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
