/**
 * Sprint Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SprintService);
  }
}(this, function(expect, SprintService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SprintService.OrganizationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganizationsApi', function() {
    describe('organizationsGet', function() {
      it('should call organizationsGet successfully', function(done) {
        //uncomment below and update the code to test organizationsGet
        //instance.organizationsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsIdDelete', function() {
      it('should call organizationsIdDelete successfully', function(done) {
        //uncomment below and update the code to test organizationsIdDelete
        //instance.organizationsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsIdGet', function() {
      it('should call organizationsIdGet successfully', function(done) {
        //uncomment below and update the code to test organizationsIdGet
        //instance.organizationsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsIdInviteUserIdDelete', function() {
      it('should call organizationsIdInviteUserIdDelete successfully', function(done) {
        //uncomment below and update the code to test organizationsIdInviteUserIdDelete
        //instance.organizationsIdInviteUserIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsIdInviteUserIdPost', function() {
      it('should call organizationsIdInviteUserIdPost successfully', function(done) {
        //uncomment below and update the code to test organizationsIdInviteUserIdPost
        //instance.organizationsIdInviteUserIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsIdPatch', function() {
      it('should call organizationsIdPatch successfully', function(done) {
        //uncomment below and update the code to test organizationsIdPatch
        //instance.organizationsIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsPost', function() {
      it('should call organizationsPost successfully', function(done) {
        //uncomment below and update the code to test organizationsPost
        //instance.organizationsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
