/**
 * node-express-boilerplate API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NodeExpressBoilerplateApiDocumentation);
  }
}(this, function(expect, NodeExpressBoilerplateApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NodeExpressBoilerplateApiDocumentation.TeamsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TeamsApi', function() {
    describe('teamsGet', function() {
      it('should call teamsGet successfully', function(done) {
        //uncomment below and update the code to test teamsGet
        //instance.teamsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsIdDelete', function() {
      it('should call teamsIdDelete successfully', function(done) {
        //uncomment below and update the code to test teamsIdDelete
        //instance.teamsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsIdGet', function() {
      it('should call teamsIdGet successfully', function(done) {
        //uncomment below and update the code to test teamsIdGet
        //instance.teamsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsIdPatch', function() {
      it('should call teamsIdPatch successfully', function(done) {
        //uncomment below and update the code to test teamsIdPatch
        //instance.teamsIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsPost', function() {
      it('should call teamsPost successfully', function(done) {
        //uncomment below and update the code to test teamsPost
        //instance.teamsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
